// Project repository (T5): CRUD over the projects table.

import type { DatabaseSync } from "node:sqlite";
import type { Project } from "@hpath/contract";
import { NotFoundError, translateConstraintError } from "../errors.js";

interface ProjectRow {
  id: string;
  name: string;
  repo_url: string;
  created_at: string;
}

function toProject(row: ProjectRow): Project {
  return {
    id: row.id,
    name: row.name,
    repoUrl: row.repo_url,
    createdAt: row.created_at,
  };
}

export class ProjectRepository {
  constructor(private readonly db: DatabaseSync) {}

  /** Insert a fully-formed project (ids are generated by callers). */
  create(project: Project): Project {
    try {
      this.db
        .prepare("INSERT INTO projects (id, name, repo_url, created_at) VALUES (?, ?, ?, ?)")
        .run(project.id, project.name, project.repoUrl, project.createdAt);
    } catch (err) {
      throw translateConstraintError(err, `create project "${project.name}"`);
    }
    return project;
  }

  get(id: string): Project | undefined {
    const row = this.db.prepare("SELECT * FROM projects WHERE id = ?").get(id);
    return row ? toProject(row as unknown as ProjectRow) : undefined;
  }

  /** Like get, but throws NotFoundError when missing (handler convenience). */
  getRequired(id: string): Project {
    const project = this.get(id);
    if (!project) {
      throw new NotFoundError(`project not found: ${id}`);
    }
    return project;
  }

  exists(id: string): boolean {
    return this.get(id) !== undefined;
  }

  /** All projects, oldest first. */
  list(): Project[] {
    const rows = this.db
      .prepare("SELECT * FROM projects ORDER BY created_at, id")
      .all();
    return rows.map((row) => toProject(row as unknown as ProjectRow));
  }
}
