// Project repository (T5): CRUD over the projects table. DeleteProject
// cascades: the projects graph (envs / cases / runs / assets) is RESTRICT by
// design, so removeCascade deletes children in dependency order inside one
// transaction and reports the artifact-store keys to purge after the commit.

import type { DatabaseSync } from "node:sqlite";
import type { Project } from "@hpath/contract";
import { NotFoundError, translateConstraintError } from "../errors.js";
import { withTransaction } from "../database.js";

interface ProjectRow {
  id: string;
  name: string;
  repo_url: string;
  created_at: string;
}

function toProject(row: ProjectRow): Project {
  return {
    id: row.id,
    name: row.name,
    repoUrl: row.repo_url,
    createdAt: row.created_at,
  };
}

export interface CascadeDeleteResult {
  /** Artifact-store keys whose bytes should be purged after the commit. */
  artifactKeys: string[];
  /** Rows removed per child table (for logging / tests). */
  counts: { runs: number; cases: number; envs: number; assets: number };
}

export class ProjectRepository {
  constructor(private readonly db: DatabaseSync) {}

  /** Insert a fully-formed project (ids are generated by callers). */
  create(project: Project): Project {
    try {
      this.db
        .prepare("INSERT INTO projects (id, name, repo_url, created_at) VALUES (?, ?, ?, ?)")
        .run(project.id, project.name, project.repoUrl, project.createdAt);
    } catch (err) {
      throw translateConstraintError(err, `create project "${project.name}"`);
    }
    return project;
  }

  get(id: string): Project | undefined {
    const row = this.db.prepare("SELECT * FROM projects WHERE id = ?").get(id);
    return row ? toProject(row as unknown as ProjectRow) : undefined;
  }

  /** Like get, but throws NotFoundError when missing (handler convenience). */
  getRequired(id: string): Project {
    const project = this.get(id);
    if (!project) {
      throw new NotFoundError(`project not found: ${id}`);
    }
    return project;
  }

  exists(id: string): boolean {
    return this.get(id) !== undefined;
  }

  /** All projects, oldest first. */
  list(): Project[] {
    const rows = this.db
      .prepare("SELECT * FROM projects ORDER BY created_at, id")
      .all();
    return rows.map((row) => toProject(row as unknown as ProjectRow));
  }

  /** Replace the mutable fields. Unique-name conflicts map to ConflictError. */
  update(id: string, fields: { name: string; repoUrl: string }): Project {
    const existing = this.getRequired(id);
    try {
      this.db
        .prepare("UPDATE projects SET name = ?, repo_url = ? WHERE id = ?")
        .run(fields.name, fields.repoUrl, id);
    } catch (err) {
      throw translateConstraintError(err, `update project "${fields.name}"`);
    }
    return { ...existing, name: fields.name, repoUrl: fields.repoUrl };
  }

  /**
   * Delete a project and everything under it in one transaction: runs (their
   * events + artifact records cascade), cases (alignments + changelog
   * cascade), envs, assets, finally the project itself. Returns the artifact
   * store keys whose bytes the caller should purge best-effort after the
   * commit — the store sits outside the database, so bytes cannot be part of
   * the transaction.
   */
  removeCascade(id: string): CascadeDeleteResult {
    this.getRequired(id);
    return withTransaction(this.db, () => {
      const artifactRows = this.db
        .prepare(
          "SELECT artifacts.key AS key FROM artifacts JOIN runs ON runs.id = artifacts.run_id "
            + "WHERE runs.project_id = ?",
        )
        .all(id);
      const artifactKeys = artifactRows.map((row) => (row as { key: string }).key);
      // Assets store a manifest of every file the upload wrote (JSON array of
      // {filename, key}); the legacy content_ref stays the fallback.
      const assetRows = this.db
        .prepare("SELECT content_ref, content_refs_json FROM assets WHERE project_id = ?")
        .all(id);
      for (const row of assetRows) {
        const typed = row as { content_ref: string; content_refs_json: string };
        if (typed.content_refs_json) {
          try {
            const parsed: unknown = JSON.parse(typed.content_refs_json);
            if (Array.isArray(parsed)) {
              for (const entry of parsed) {
                const key = (entry as { key?: unknown }).key;
                if (typeof key === "string" && key !== "") artifactKeys.push(key);
              }
            }
          } catch {
            // Falls through to the content_ref fallback below.
          }
        }
        if (typed.content_ref) {
          artifactKeys.push(typed.content_ref);
        }
      }

      const deleteByProject = (table: string): number => {
        const info = this.db.prepare(`DELETE FROM ${table} WHERE project_id = ?`).run(id);
        return Number(info.changes);
      };
      // Children first: runs pin env and case, so they must go before both.
      const counts = {
        runs: deleteByProject("runs"),
        cases: deleteByProject("cases"),
        envs: deleteByProject("envs"),
        assets: deleteByProject("assets"),
      };
      const info = this.db.prepare("DELETE FROM projects WHERE id = ?").run(id);
      if (Number(info.changes) === 0) {
        throw new NotFoundError(`project not found: ${id}`);
      }
      return { artifactKeys, counts };
    });
  }
}
